name: AAAAHHHHHHHHHHHH!!!!!!!!!!

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Validate wrapper, restore Gradle™ cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle™™
        run: ./gradlew clean build

      - name: Upload artifacts™
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs